const dummyText = `Cat ipsum dolor sit amet, eum or ex yet eum but sequi. Dolorem excepteur so sunt, so cillum or autem. Eiusmod rem numquam laudantium. Officia ipsa yet exercitation quaerat nemo ipsa. Mollit aspernatur esse for magna nostrum yet beatae or consequat. Magni. Eius quaerat odit dolores nemo. Officia nihil numquam. Cillum autem for vel ullam. Pariatur. Nulla mollit quia but vitae or dicta. Adipisci ullam and aperiam sed or quae enim and sint. Corporis dolores so occaecat so magni, laborum. Doloremque id ex, so deserunt, yet aliquam yet rem. Laboriosam. Labore ipsam or aliquid doloremque esse, for quisquam or magna. Nequeporro magnam or eum. Velit vel. Culpa aperiam architecto and nisi or ea aliquip quis. Sint. Nostrud.


Ratione duis odit yet eos and unde so explicabo id. Architecto laboris but amet but nequeporro lorem amet but vitae. Ex sunt so in. Sint veniam so laborum inventore magnam quasi. Laboriosam mollit esse aliquid ipsa. Cupidatat nisi laborum but occaecat ut. Do eu or dolores and dolorem.

Dolor quasi yet lorem. Consequatur sunt but dolores cupidatat or laudantium. Adipisicing eos. Eiusmod totam but laboris so dicta cillum but suscipit. Eos nequeporro amet. Eum eius for modi but accusantium, aspernatur ipsum but ullam. Irure dolore but aperiam yet rem dolore for non. Aliquid culpa. Laudantium et cupidatat. Eos nulla yet do laudantium but minim nulla. Perspiciatis cupidatat but iste. Consequatur inventore sunt. Sit id, natus. Duis voluptas. Illo ipsam ratione nostrum so lorem for ratione non. Architecto officia for quisquam yet sequi yet amet so nihil but veniam. Qui.

Dolor quasi yet lorem. Consequatur sunt but dolores cupidatat or laudantium. Adipisicing eos. Eiusmod totam but laboris so dicta cillum but suscipit. Eos nequeporro amet. Eum eius for modi but accusantium, aspernatur ipsum but ullam. Irure dolore but aperiam yet rem dolore for non. Aliquid culpa. Laudantium et cupidatat. Eos nulla yet do laudantium but minim nulla. Perspiciatis cupidatat but iste. Consequatur inventore sunt. Sit id, natus. Duis voluptas. Illo ipsam ratione nostrum so lorem for ratione non. Architecto officia for quisquam yet sequi yet amet so nihil but veniam. Qui.

Dolor quasi yet lorem. Consequatur sunt but dolores cupidatat or laudantium. Adipisicing eos. Eiusmod totam but laboris so dicta cillum but suscipit. Eos nequeporro amet. Eum eius for modi but accusantium, aspernatur ipsum but ullam. Irure dolore but aperiam yet rem dolore for non. Aliquid culpa. Laudantium et cupidatat. Eos nulla yet do laudantium but minim nulla. Perspiciatis cupidatat but iste. Consequatur inventore sunt. Sit id, natus. Duis voluptas. Illo ipsam ratione nostrum so lorem for ratione non. Architecto officia for quisquam yet sequi yet amet so nihil but veniam. Qui.`;

export default dummyText;
